### ISSUE TITLE
(Version Conflicted) Login Backend Logic and Authorization

### ISSUE THREAD

**Issue by egecenberci** [Project-Yicem/Yicem-backend#11]
### Tasks

- [x] Implement login functionality
- [x] Generate JWT tokens
- [x] Secure the application (check JWT tokens for API endpoints)
- [x] Resolve deprecated method issues
- [x] Resolve version issues and integrate the functionality
